name: SMP-Core
author: Trae
main: me.trae.smp.Main
version: 1.0.0
load: STARTUP
api-version: 1.13
commands:
  client:
  ping:
  smpreload:
  playtime:
  list:
    aliases: [ players, online ]
  sethome:
    aliases: [ sh ]
  delhome:
    aliases: [ dh ]
  home:
    aliases: [ h ]
  back:
    aliases: [ b ]
  help:
  dye:
    aliases: [ color, colour ]
  statistics:
    aliases: [ stats, info ]
  alts:
    aliases: [ checkalts, searchalts ]
  observer:
    aliases: [ obs ]
  explosionheal:
    aliases: [ tntheal, creeperheal ]
  tpa:
  tpaccept: